---
title: "狂言"
subtitle: "『魚説経』、『濯ぎ川』"
pagetitle: "二二二_狂言"
author:
  name: "Shuntaro Ono"
format: 
  html:
    embed-resources: true
    code-copy: true
    code-fold: true
    code-overflow: scroll
    number-sections: true
    smooth-scroll: true
    toc: true
    toc-location: left
    toc-title: Contents
date: 2024/08/04
editor: visual
include-after-body: "footer.html"
title-block-banner: "#70A9CF"
title-block-banner-color: "black"
---

<p style="text-align: center;">
  <a href="https://www.instagram.com/shun_o_7" class="custom-instagram-icon"> [{{< fa brands instagram size=2x >}}]{style="color:#833AB4"}
  </a>
</p>

# 魚説経

## あらすじ

　現在の神戸で暮らしていたとある漁師の男は、漁師という生業に疲れてしまい僧侶になります。そんな男がある日、ふと都見物をしてみたいということで上京します。一方、京都に暮らす別の男は最近建てた持仏堂の住職のなり手を探していました。そんな二人が道中偶然出会い、京都の男が僧侶になった男を持仏堂に案内します。案内されたところで早速説経(説法)をするように言われた男。お経など知る由もなく途方に暮れた男はあることを思い立ちます、、

## "創作説法"の抜粋

　いでいで鰆([サワラ](https://www.zukan-bouz.com/com/%E3%82%B5%E3%83%AF%E3%83%A9){style="color:red;"})、説法を述べむと、烏賊([イカ]{style="color:red;"})にも、鱸([スズキ](https://www.zukan-bouz.com/syu/%E3%82%B9%E3%82%BA%E3%82%AD){style="color:red;"})に煤けたる、黒鯛([クロダイ](https://www.zukan-bouz.com/syu/%E3%82%AF%E3%83%AD%E3%83%80%E3%82%A4){style="color:red;"})の衣に、乾鮭([シャケ](https://www.zukan-bouz.com/com/%E3%82%B5%E3%82%B1){style="color:red;"})色の袈裟を着し、水晶の数珠を蛤([ハマグリ](https://www.zukan-bouz.com/syu/%E3%83%8F%E3%83%9E%E3%82%B0%E3%83%AA){style="color:red;"})、高麗鮫([サメ](https://www.zukan-bouz.com/com/%E3%82%B5%E3%83%A1){style="color:red;"})の上へ、熨斗([ノシ]{style="color:red;"})熨斗[^1]と鮠([ハヤ/ハエ](https://www.zukan-bouz.com/syu/%E3%82%AA%E3%82%A4%E3%82%AB%E3%83%AF){style="color:red;"})上がり、金海鼠([キンコ]{style="color:red;"})を鳴らし、又鰐口([ワニゴチ](https://www.zukan-bouz.com/syu/%E3%83%AF%E3%83%8B%E3%82%B4%E3%83%81){style="color:red;"})を泥鰌([ドジョウ](https://www.zukan-bouz.com/com/%E3%83%89%E3%82%B8%E3%83%A7%E3%82%A6){style="color:red;"})泥鰌と打ち鳴らし、まず説法を鯣([スルメ](https://www.zukan-bouz.com/syu/%E3%82%B9%E3%83%AB%E3%83%A1%E3%82%A4%E3%82%AB){style="color:red;"})なり。ちょうじも早く鯊([ハゼ](https://www.zukan-bouz.com/com/%E3%83%8F%E3%82%BC){style="color:red;"})集まり、心の海月([クラゲ](https://www.zukan-bouz.com/syu/%E3%83%93%E3%82%BC%E3%83%B3%E3%82%AF%E3%83%A9%E3%82%B2){style="color:red;"})を赤鱏([エイ](https://www.zukan-bouz.com/com/%E3%82%A8%E3%82%A4){style="color:red;"})にし、又鯱([シャチ]{style="color:red;"})の如きも、鰻([ウナギ](https://www.zukan-bouz.com/com/%E3%82%A6%E3%83%8A%E3%82%AE){style="color:red;"})の穴より出るが如く、ヌラヌラとして仏の御海苔([ノリ]{style="color:red;"})を聴聞すべし。

[^1]: 熨斗鮑(ノシアワビ)は、アワビの肉を薄く剥ぎ、長く伸ばしたもの。古くは儀式用の肴に用い、のちに祝儀の贈り物に添える風習となった。現代、私たちが普段目にしている熨斗袋はこの風習の名残。

　それ人間の果敢なき命は海老([エビ](https://www.zukan-bouz.com/syu/%E3%82%A2%E3%82%AB%E3%82%A8%E3%83%93){style="color:red;"})の眼を力となし、海月([クラゲ]{style="color:red;"})が海に浮かみ漂うが如く、浮世を渡る人間世界なり。つつぎり敬っても魚([ウオ]{style="color:red;"})、ちぬ鯛([チヌダイ](https://www.zukan-bouz.com/syu/%E3%82%AF%E3%83%AD%E3%83%80%E3%82%A4){style="color:red;"})教主、鮭([サケ]{style="color:red;"})鰤([ブリ](https://www.zukan-bouz.com/syu/%E3%83%96%E3%83%AA){style="color:red;"})如来。鰤([ブリ]{style="color:red;"})子の菩薩に申して申鯖([サバ](https://www.zukan-bouz.com/com/%E3%82%B5%E3%83%90){style="color:red;"})、鰈([カレイ](https://www.zukan-bouz.com/com/%E3%82%AB%E3%83%AC%E3%82%A4){style="color:red;"})教を習うとも、鯰([ナマズ](https://www.zukan-bouz.com/com/%E3%83%8A%E3%83%9E%E3%82%BA){style="color:red;"})には習うべからず。ただ鯉([コイ]{style="color:red;"})願うところは、鮒([フナ](https://www.zukan-bouz.com/syu/%E3%83%8B%E3%82%B4%E3%83%AD%E3%83%96%E3%83%8A){style="color:red;"})落世界へ、鯒([コチ](https://www.zukan-bouz.com/syu/%E3%83%9E%E3%82%B4%E3%83%81){style="color:red;"})々と招ぜられたきなり。

　故に仏も、鮟鱇([アンコウ](https://www.zukan-bouz.com/com/%E3%82%A2%E3%83%B3%E3%82%B3%E3%82%A6){style="color:red;"})の御海苔([ノリ]{style="color:red;"})を成し給うも、これ皆小魚([ウオ]{style="color:red;"})の為なれば、子たるもの、海鼠([ナマコ]{style="color:red;"})、梭魚([カマス](https://www.zukan-bouz.com/syu/%E3%82%A2%E3%82%AB%E3%82%AB%E3%83%9E%E3%82%B9){style="color:red;"})子、雑魚([ザコ]{style="color:red;"})、鱚([キス](https://www.zukan-bouz.com/syu/%E3%82%B7%E3%83%AD%E3%82%AE%E3%82%B9){style="color:red;"})子、諸子([モロコ](https://www.zukan-bouz.com/syu/%E3%83%9B%E3%83%B3%E3%83%A2%E3%83%AD%E3%82%B3){style="color:red;"})、鰤([ブリ]{style="color:red;"})子、金海鼠([キンコ]{style="color:red;"})、鮞([ハララゴ]{style="color:red;"})[^2]、炒子([イリコ]{style="color:red;"})^[煮干しのこと。]、鮬([セイゴ](https://www.zukan-bouz.com/syu/%E3%82%B9%E3%82%BA%E3%82%AD){style="color:red;"})、かく大勢の数の子([カズノコ]{style="color:red;"})も、親に対し鰊([ニシン](https://www.zukan-bouz.com/syu/%E3%83%8B%E3%82%B7%E3%83%B3){style="color:red;"})あらば、これ大いなる鱶([フカ](https://www.zukan-bouz.com/syu/%E3%83%9B%E3%82%B7%E3%82%B6%E3%83%A1){style="color:red;"})なり、誠に親の血引([チビキ](https://www.zukan-bouz.com/syu/%E3%83%8F%E3%83%81%E3%83%93%E3%82%AD){style="color:red;"})とて、糸よりの様な細き心にて、雨の魚([アメノウオ](https://www.zukan-bouz.com/syu/%E3%82%A2%E3%83%9E%E3%82%B4){style="color:red;"})の如く涙を鱈([タラ](https://www.zukan-bouz.com/com/%E3%82%BF%E3%83%A9){style="color:red;"})々と流し、鮫([サメ]{style="color:red;"})々と泣く。されば観音経の文に曰く、干鯛([ヒダイ](https://www.zukan-bouz.com/syu/%E3%83%98%E3%83%80%E3%82%A4){style="color:red;"})平らげ、海老([エビ]{style="color:red;"})観音力とも説かれたり。又心経の文に曰く、あのく蛸([タコ]{style="color:red;"})三百三文鯛([タイ]{style="color:red;"})。鰊([ニシン]{style="color:red;"})般若、鮑([アワビ](https://www.zukan-bouz.com/syu/%E3%82%A2%E3%82%AB%E3%82%A2%E3%83%AF%E3%83%93){style="color:red;"})陀心経。

[^2]: 魚卵のこと。特にサケの卵であるイクラを指す。

　今日の殺生これまでなり。雁木([ガンギ](https://www.zukan-bouz.com/syu/%E3%82%BD%E3%82%B3%E3%82%AC%E3%83%B3%E3%82%AE%E3%82%A8%E3%82%A4){style="color:red;"})河豚([フグ]{style="color:red;"})毒、ぎちゅう一栄螺([サザエ](https://www.zukan-bouz.com/syu/%E3%82%B5%E3%82%B6%E3%82%A8){style="color:red;"})、鰹([カツオ](https://www.zukan-bouz.com/syu/%E3%82%AB%E3%83%84%E3%82%AA){style="color:red;"})こしょ鯛([コショウダイ](https://www.zukan-bouz.com/syu/%E3%82%B3%E3%82%B7%E3%83%A7%E3%82%A6%E3%83%80%E3%82%A4){style="color:red;"})ぐんりょう。生蛸([タコ]{style="color:red;"})々々々々。鱧([ハモ](https://www.zukan-bouz.com/syu/%E3%83%8F%E3%83%A2){style="color:red;"})阿弥陀、鱧([ハモ]{style="color:red;"})阿弥陀、鱧([ハモ]{style="color:red;"})阿弥陀、、、鱧([ハモ]{style="color:red;"})鮎([アユ]{style="color:red;"})蛸([タコ]{style="color:red;"})！

------------------------------------------------------------------------

# 濯ぎ川

## あらすじ

　裏の川で洗濯をしている聟は、妻と姑がガミガミと用事を言いつけに来るのに堪えかね、用事はすべて紙に書いてもらい、そのほかのことはしなくてよいという取り決めをします。と、その時、小袖が川に流れ、拾おうとした妻が溺れて助けを求められますが、「そんなことは書き付けにあったっけ？」とのんきに構える聟。結局、これからはガミガミ言わないと約束させ、妻を助けるのですが、結局はすぐ助けなかったことを妻になじられ、元の木阿弥……という、狂言の「恐妻もの」の典型とも言えます。

## トリビア

　作者は劇作家の飯沢匡で、16世紀フランス小咄「ル・キュヴィエ（洗濯桶）」をもとに新劇用に書いたものを、茂山家で狂言用にアレンジし、上演するようになりました。初演は、1953（昭和28）年、演出は、戦後の古典芸能の再興に尽力した武智鉄二が当たっています。

　狂言の世界では、明治時代以降に書かれた作品は全部「新作」に分類されます。いや、最早古典やんとツッコミたくなりますが、、
